language: java
jdk: oraclejdk11

install: true
script: mvn install

after_success:
- pwd
- mkdir $HOME/build
- ls -l
- cd $HOME/build
- pwd
- ls -l
- git config --global user.email "testxyz@gmail.com"
- git config --global user.name "okadevi"
- git clone --depth=50 --branch=master https://github.com/okadevi/mongo-springboot-poc
- cd mongo-springboot-poc
- ls -l
- cp -r C:/Users/Dev/Desktop/github/mongo-springboot-poc/iom/target $HOME/build/mongo-springboot-poc
- ls -l
- git add -f .
- git remote rm origin
- git remote add origin https://okadevi:$GITHUB_API_KEY@github.com/okadevi/mongo-springboot-poc.git
- git add -f .
- git commit -m "travis integration"
- git push -fq origin master
- echo -e "Done......\n"
